In [ ]:
import numpy as np

In [ ]:
np.zeros(7)


array([0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
np.empty(5)


array([1., 1., 1., 1., 1.])

In [ ]:
np.full((2,2),4)

array([[4, 4],
       [4, 4]])

In [ ]:
a=np.array([1,2,7,4,'3'])
a

array(['1', '2', '7', '4', '3'], dtype='<U11')

In [ ]:
np.array([3,2,1,3.0])

array([3., 2., 1., 3.])

In [ ]:
np.array([1,3,5,'Zahid o a'],dtype=np.float32)

ValueError: could not convert string to float: 'Zahid o a'

In [ ]:
np.arange(2,11,2)


array([ 2,  4,  6,  8, 10])

In [ ]:
np.identity(5,)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(5,5,-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [ ]:
a = np.array([[5,10,5,25],[1,20,25,20]])

In [ ]:
print(a)
b=np.append(a,[1,3])
b

[[ 5 10  5 25]
 [ 1 20 25 20]]


array([ 5, 10,  5, 25,  1, 20, 25, 20,  1,  3])

In [ ]:
np.delete(a,0)

array([10,  5, 20, 25, 20])

In [ ]:
print(a,'\n\n',np.sort(a),'\n\n',np.sort(a,axis=0))

[[ 5 10  5 25]
 [ 1 20 25 20]] 

 [[ 5  5 10 25]
 [ 1 20 20 25]] 

 [[ 1 10  5 20]
 [ 5 20 25 25]]


In [ ]:
a = np.array([[5,10,5,25],[1,20,25,20]])
b=a
print(a)
b[0,0]=2
print(a)

[[ 5 10  5 25]
 [ 1 20 25 20]]
[[ 2 10  5 25]
 [ 1 20 25 20]]


In [ ]:
a = np.array([[5,10,5,25],[1,20,25,20]])
b=a.copy()
print(a)
b[0,0]=2
print(a)

[[ 5 10  5 25]
 [ 1 20 25 20]]
[[ 5 10  5 25]
 [ 1 20 25 20]]


In [ ]:
a = np.array([[5,10,5,25],[1,20,25,20]])

In [ ]:
a.ndim


2

In [ ]:
a.shape


(2, 4)

In [ ]:
a.size


8

In [ ]:
a = np.array([1,3,2,5,6,2,3,42,2,2,1,5])

In [ ]:
b=a.reshape(3,4)
b

array([[ 1,  3,  2,  5],
       [ 6,  2,  3, 42],
       [ 2,  2,  1,  5]])

In [ ]:
b.reshape(2,3,2)

array([[[ 1,  3],
        [ 2,  5],
        [ 6,  2]],

       [[ 3, 42],
        [ 2,  2],
        [ 1,  5]]])

In [ ]:
print(b)
b[1,0:2]

[[ 1  3  2  5]
 [ 6  2  3 42]
 [ 2  2  1  5]]


array([6, 2])

In [ ]:
print(b)
b[:,1]

[[ 1  3  2  5]
 [ 6  2  3 42]
 [ 2  2  1  5]]


array([3, 2, 2])

In [ ]:
b = b.reshape(2,2,3)

In [ ]:
print(b)
b[:,:,0]

[[[ 1  3  2]
  [ 5  6  2]]

 [[ 3 42  2]
  [ 2  1  5]]]


array([[1, 5],
       [3, 2]])

In [ ]:
print(b)
c=b.flatten()
#modifica b si hago cambios a d
d=b.ravel()

[[[ 1  3  2]
  [ 5  6  2]]

 [[ 3 42  2]
  [ 2  1  5]]]


In [ ]:
print(b)
d[0]=5
print(d)
print(b)

[[[ 1  3  2]
  [ 5  6  2]]

 [[ 3 42  2]
  [ 2  1  5]]]
[ 5  3  2  5  6  2  3 42  2  2  1  5]
[[[ 5  3  2]
  [ 5  6  2]]

 [[ 3 42  2]
  [ 2  1  5]]]


In [2]:
import numpy as np

In [3]:
a=np.arange(10,20,2)
b=np.arange(5,10,1)


In [4]:
print(a)
print(b)
print(a+b)
print(a*b)
print(a-b)
print(a/b)

[10 12 14 16 18]
[5 6 7 8 9]
[15 18 21 24 27]
[ 50  72  98 128 162]
[5 6 7 8 9]
[2. 2. 2. 2. 2.]


In [5]:
np.dot(a,b)


510

In [ ]:
print(a)
print(np.mean(a))
print(np.median(a))
print(np.std(a))

[10 12 14 16 18]
14.0
14.0
2.8284271247461903


In [ ]:
from statistics import stdev,pstdev


In [ ]:
print(np.std(a, ddof=1))
print(stdev(a))
print(pstdev(a))

3.1622776601683795
3.1622776601683795
2.8284271247461903


In [ ]:
a=np.arange(10,21,2).reshape(2,-1)
b=np.array([[2],[4]])
print(a)
print(b)
print(a+b)
print(a*b)

[[10 12 14]
 [16 18 20]]
[[2]
 [4]]
[[12 14 16]
 [20 22 24]]
[[20 24 28]
 [64 72 80]]


In [ ]:
print(a)
print(np.min(a))
print(np.max(a))
print(np.argmin(a))
print(np.argmax(a))

[[10 12 14]
 [16 18 20]]
10
20
0
5


In [ ]:
np.sqrt(a)


array([[3.16227766, 3.46410162, 3.74165739],
       [4.        , 4.24264069, 4.47213595]])

In [ ]:
print(a)
np.where(a <=12, 'Es chiquito','Es grande')

[[10 12 14]
 [16 18 20]]


array([['Es chiquito', 'Es chiquito', 'Es grande'],
       ['Es grande', 'Es grande', 'Es grande']], dtype='<U11')

In [ ]:
print(a)
np.where(a <=12, 'Es chiquito',\
         np.where(a<=15,'Es mediano',\
                  'Ahora si grande'))

[[10 12 14]
 [16 18 20]]


array([['Es chiquito', 'Es chiquito', 'Es mediano'],
       ['Ahora si grande', 'Ahora si grande', 'Ahora si grande']],
      dtype='<U15')

In [ ]:
print(a)
np.where((a<=18)&(a>11), 'Es mediano','Es extremo')


[[10 12 14]
 [16 18 20]]


array([['Es extremo', 'Es mediano', 'Es mediano'],
       ['Es mediano', 'Es mediano', 'Es extremo']], dtype='<U10')

In [ ]:
print(a)
print(b)
a==b*6


[[10 12 14]
 [16 18 20]]
[[2]
 [4]]


array([[False,  True, False],
       [False, False, False]])

In [ ]:
print(a)
a.transpose()
b=a.T

[[10 12 14]
 [16 18 20]]


In [ ]:
print(b)
np.flip(b,axis=1)


[[10 16]
 [12 18]
 [14 20]]


array([[16, 10],
       [18, 12],
       [20, 14]])