# Numpy

Texto

In [10]:
import numpy as np
import pandas as pd

In [11]:
pd.DataFrame(np.ones((2, 3)))

0    1    2
0  1.0  1.0  1.0
1  1.0  1.0  1.0

In [7]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [41]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 26 ms


In [42]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.21 s


## Creación de objetos

In [129]:
np.random.randn(2, 2, 3) # Para valores aleatorios

array([[[-0.329532  , -0.22742442,  0.61722264],
        [ 2.21210455, -1.57542876,  2.62895663]],

       [[-1.07026226, -0.09341155, -0.59112337],
        [-0.24701735,  0.33303291,  0.97928691]]])

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

Para poner varias dimensiones le pones doble paréntesis (que es realmente pasarle una tupla)

In [10]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

np.empty no genera ceros como tal. Genera un array sin algún valor en particular.

In [11]:
np.empty(5)

array([0., 0., 0., 0., 0.])

¿Qué hace np.full? Te llena con el número que le pones afuera

In [14]:
np.full((2, 2, 5), 4)

array([[[4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4]],

       [[4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4]]])

A np.array le puedes pasar un sequence-like object. Puedes pasar una lista, por ejemplo, o una lista de listas.

In [20]:
np.array([1, 2, 3, 4]) # Te permite transformar una lista a un array

array([1, 2, 3, 4])

Cuando transformas a un array, todos los elementos deben ser del mismo tipo. De lo contrario, todos (en el caso sigueinte) te los transforma a strings. 

In [28]:
np.array([1, 2, 3]) # Te permite transformar una lista a un array

array([1, 2, 3])

La versión en array de range en Python es np.arange:

In [ ]:

a = np.arange(2, 11, 2) # Se parece mucho al range normal. 
a

In [32]:
a.shape

(5,)

In [39]:
a.dtype

dtype('int32')

Le podemos agregar valores

In [52]:
b = np.append(a, [1, 2])
b

array([ 2,  4,  6,  8, 10,  1,  2])

Matrix de identidad

In [36]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
np.eye(5, 5, 1) #Le puedes mover la diagonal con unos. 

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

## Transformaciones

Podemos agregar valores:

In [45]:
b = np.append(a, [1, 2])
b

array([ 2,  4,  6,  8, 10,  1,  2])

O eliminar valores:

In [46]:
np.delete(a, 1)

array([ 2,  6,  8, 10])

Para modificar un valor en particular, especifico la coordenada:

In [53]:
print(b)
b[0] = 1
print(b)

[ 2  4  6  8 10  1  2]
[ 1  4  6  8 10  1  2]


También podría especificar un rango de coordenadas

In [66]:
b[1:4] = 11
b

array([ 5, 11, 11, 11, 10,  1,  2])

Igual, para acceder a un valor, ponemos la coordenada:

In [77]:
rat = np.identity(5)
rat

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [88]:
print(rat[0][0])
print(rat[1][0])

1.0
0.0


In [90]:
print(rat[0, 0]) # Es equivalente a lo que venía antes.
print(rat[1, 0])
print(rat[2, 0:4])

1.0
0.0
[0. 0. 1. 0.]


Podemos haer copias para evitar modificar el original:

In [54]:
c = b.copy()

In [55]:
d = b
d[0] = 5
print(b)

[ 5  4  6  8 10  1  2]


Para cambiar el tipo de datos en el array usamos array.astype('float'). Esto siempre te crea una copia.

In [64]:
c.astype('int')

array([ 1,  4,  6,  8, 10,  1,  2])

Para cambiar las dimensiones de array usamos array.reshape(). Esta forma tiene que "concordar" con los datos que tenemos.

In [108]:
aa = np.array([[1, 456, 8, 7, 3, 23, 1], [1, 2, 234, 345, 1, 1, 1]])

In [110]:
aa.reshape(7, 2)

array([[  1, 456],
       [  8,   7],
       [  3,  23],
       [  1,   1],
       [  2, 234],
       [345,   1],
       [  1,   1]])

Podríamos también usar transpose:

In [112]:
aa.transpose()

array([[  1,   1],
       [456,   2],
       [  8, 234],
       [  7, 345],
       [  3,   1],
       [ 23,   1],
       [  1,   1]])

In [113]:
aa.T

array([[  1,   1],
       [456,   2],
       [  8, 234],
       [  7, 345],
       [  3,   1],
       [ 23,   1],
       [  1,   1]])

Para aplanar todos los valores usamos array.flatten()

In [91]:
rat

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [92]:
rat.flatten()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

## Operaciones

In [62]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
arr2 = np.array([[0, 4, 1], [7, 2, 12]])
arr2

array([[ 0,  4,  1],
       [ 7,  2, 12]])

Comparaciones entre arrays te dan booleans

In [59]:
arr > arr2

array([[ True, False,  True],
       [False,  True, False]])

Operaciones entre arrays de mismo tamaño se hacen element-wise

In [60]:
arr + arr2

array([[ 1,  6,  4],
       [11,  7, 18]])

Puedes sacar otras cifras estadísticas:

In [122]:
print(np.mean(arr))
print(np.std(arr))
print(np.min(arr))
print(np.argmin(arr)) # Te dice la posición del valor mínimo
print(np.argmax(arr))

3.5
1.707825127659933
1
0
5


In [130]:
np.random.randn(2, 3)

array([[ 0.70848885, -1.09986907, -1.09651228],
       [ 0.08055364,  0.36999867,  0.45238082]])

Un equivalente al IF es el np.where. Pones (condición, resultado si sí, resultado si no).

In [132]:
a

array([ 2,  4,  6,  8, 10])

In [133]:
np.where( a <= 5, 'Pequeño', 'Grande')

array(['Pequeño', 'Pequeño', 'Grande', 'Grande', 'Grande'], dtype='<U7')

In [134]:
a = 14
b = 4
  
print(b and a) # print_stat1
print(b & a) # print_stat2

14
4


In [ ]:
A